BEGIN TRANSACTION;
ALTER TABLE link DROP CONSTRAINT link_dst_fkey, ADD CONSTRAINT link_dst_fkey FOREIGN KEY (dst) REFERENCES url (url) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE link DROP CONSTRAINT link_dst_fkey, ADD CONSTRAINT link_dst_fkey FOREIGN KEY (dst) REFERENCES url (url) ON UPDATE CASCADE ON DELETE CASCADE;
UPDATE parameters SET value='2' WHERE name = 'version' AND value = '1';
COMMIT;
